spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=ODA;Encrypt=True;trustServerCertificate=True;Authentication=SqlPassword
    username: sa
    password: YourStrong!Passw0rd
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    hikari:
      maximum-pool-size: 10

server:
  port: 10000

logging:
  level:
    root: INFO
    com.zaxxer.hikari: INFO
    org.springframework.jdbc: INFO
